name: CI

on:
  workflow_dispatch:
  push:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: armand-sauzay/actions-python/test@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-flags: --version
  etl-job:
    name: Etl_Job
    runs-on: ubuntu-latest
    steps:
      - name: Run file upload for etl job
        uses: ./scripts/upload-to-s3.sh
         